### ISSUE TITLE
Cannot install streamly

### ISSUE THREAD

**Issue by ghost** [brianmario/streamly#5]
OS: Linux Ubuntu 14.04 32bit (On Vagrant)
Ruby: 2.2.1

```
 gem install streamly
Fetching: streamly-0.1.4.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing streamly:
        ERROR: Failed to build gem native extension.

    /home/vagrant/.rvm/rubies/ruby-2.2.1/bin/ruby -r ./siteconf20150630-10213-1j1a323.rb extconf.rb
checking for rb_thread_blocking_region()... no
checking for rb_trap_immediate in ruby.h,rubysig.h... no
checking for curl-config... yes
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling streamly.c
In file included from streamly.h:47:0,
                 from streamly.c:23:
/home/vagrant/.rvm/rubies/ruby-2.2.1/include/ruby-2.2.0/ruby/backward/rubysig.h:14:2: warning: #warning rubysig.h is obsolete [-Wcpp]
In file included from streamly.c:23:0:
streamly.h: In function `rb_thread_blocking_region':
streamly.h:59:3: error: `TRAP_BEG' undeclared (first use in this function)
streamly.h:59:3: note: each undeclared identifier is reported only once for each function it appears in
streamly.h:61:3: error: `TRAP_END' undeclared (first use in this function)
streamly.c: In function `each_http_header':
streamly.c:103:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
streamly.c:113:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
streamly.c: In function `rb_streamly_init':
streamly.c:250:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
streamly.c:261:5: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
make: *** [streamly.o] Error 1

make failed, exit code 2

Gem files will remain installed in /home/vagrant/.rvm/gems/ruby-2.2.1/gems/streamly-0.1.4 for inspection.
Results logged to /home/vagrant/.rvm/gems/ruby-2.2.1/extensions/x86-linux/2.2.0/streamly-0.1.4/gem_make.out
```

**Comment by oleander** [comment]
It works using Ruby 2.0

**Comment by specht** [comment]
It doesn't work with ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-linux] or ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux].
